### ! Login Admin
POST http://localhost:3000/api/v1/auth/super-admin
Content-Type: application/json

{
    "email": "Karananimesh144@gmail.com",
    "password": "Karan@144#"
}

###! Admin Logout
POST http://localhost:3000/api/v1/auth/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwZmM3OTQ2Ni05ZmMwLTQ4MTQtOTMwOS05OTM1M2RkODI3Y2QiLCJhY3RvclR5cGUiOiJzdXBlcl9hZG1pbiIsImlhdCI6MTc3MjE5ODM2OCwiZXhwIjoxNzcyMjg0NzY4fQ.s3APyWq8lu-wStmpvorEX4SWtiNY2KgCb0NhNqgl8Yo

### ! School Login
POST http://localhost:3000/api/v1/auth/school
Content-Type: application/json

{
    "email": "schooladmin@test.com",
    "password": "Admin@123#"
}

###! Parent otp generator
POST http://localhost:3000/api/v1/auth/parent/send-otp
Content-Type: application/json

{
    "phone": "6294690079"
}

###! Parent otp verify
POST http://localhost:3000/api/v1/auth/parent/verify-otp
Content-Type: application/json

{
    "phone": "6294690079",
    "otp": "733146"
}