### ! Login Admin
POST http://localhost:3000/api/v1/auth/super-admin
Content-Type: application/json

{
    "email": "Karananimesh144@gmail.com",
    "password": "Karan@144#"
}

###! Admin Logout
POST http://localhost:3000/api/v1/auth/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwNDkwMmI2ZS1mYTdhLTQ2MTMtODgxYS00YjJlYjZlNGQyYTUiLCJyb2xlIjoiUEFSRU5UIiwiYWN0b3JUeXBlIjoicGFyZW50IiwiaWF0IjoxNzcyNzkwOTMzLCJleHAiOjE3NzI4NzczMzN9.J5NSmGhR6TUeCoTE6xPin-_m8rE8qGPsnntsJSnUz4w

### ! School Login
POST http://localhost:3000/api/v1/auth/school
Content-Type: application/json

{
    "email": "schooladmin@test.com",
    "password": "Admin@123#"
}

###! Parent otp generator
POST http://localhost:3000/api/v1/auth/parent/send-otp
Content-Type: application/json

{
    "phone": "6294690079"
}

###! Parent otp verify
POST http://localhost:3000/api/v1/auth/parent/verify-otp
Content-Type: application/json

{
    "phone": "6294690079",
    "otp": "733146"
}